FIND_PATH(SSVLUAWRAPPER_INCLUDE_DIR
  NAMES SSVLuaWrapper/SSVLuaWrapper.h
  PATH_SUFFIXES include/
  PATHS "${PROJECT_SOURCE_DIR}/../SSVLuaWrapper/"
  "${PROJECT_SOURCE_DIR}/extlibs/SSVLuaWrapper/"
  ${SSVLUAWRAPPER_ROOT}
  $ENV{SSVLUAWRAPPER_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound SSVLuaWrapper include at: ${SSVLUAWRAPPER_INCLUDE_DIR}.\n")

FIND_LIBRARY(SSVLUAWRAPPER_LIBRARY
  NAMES SSVLuaWrapper libSSVLuaWrapper SSVLuaWrapper-s libSSVLuaWrapper-s ssvluawrapper libssvluawrapper ssvluawrapper-s libssvluawrapper-s
  PATH_SUFFIXES lib/ lib64/
  PATHS "${PROJECT_SOURCE_DIR}/../SSVLuaWrapper/"
  "${PROJECT_SOURCE_DIR}/extlibs/SSVLuaWrapper/"
  ${SSVLUAWRAPPER_ROOT}
  $ENV{SSVLUAWRAPPER_ROOT}
  /usr/local/
  /usr/
  /sw/       
  /opt/local/
  /opt/csw/  
  /opt/
)

message("\nFound SSVLuaWrapper library at: ${SSVLUAWRAPPER_LIBRARY}.\n")

IF(SSVLUAWRAPPER_LIBRARY AND SSVLUAWRAPPER_INCLUDE_DIR)
  SET(SSVLUAWRAPPER_LIBRARIES ${SSVLUAWRAPPER_LIBRARY})
  SET(SSVLUAWRAPPER_FOUND TRUE)
ELSE(SSVLUAWRAPPER_LIBRARY AND SSVLUAWRAPPER_INCLUDE_DIR)
  SET(SSVLUAWRAPPER_FOUND FALSE)
ENDIF(SSVLUAWRAPPER_LIBRARY AND SSVLUAWRAPPER_INCLUDE_DIR)

IF(SSVLUAWRAPPER_FOUND)
  MESSAGE(STATUS "Found SSVLuaWrapper in ${SSVLUAWRAPPER_INCLUDE_DIR}")
ELSE(SSVLUAWRAPPER_FOUND)
  IF(SSVLUAWRAPPER_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could not find SSVLuaWrapper library")
  ENDIF(SSVLUAWRAPPER_FIND_REQUIRED)
ENDIF(SSVLUAWRAPPER_FOUND)

MARK_AS_ADVANCED(
  SSVLUAWRAPPER_LIBRARY
  SSVLUAWRAPPER_INCLUDE_DIR
)
